jobs:
  include:
  - stage: test
    os: linux
    dist: xenial
    language: python
    python: 3.7
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - CC=gcc-7
    - CXX=g++-7
    - CONAN_PROFILE=linux-gcc7-amd64
    - CONAN_LIBCXX_VERSION=libstdc++11
    - PIP=pip
    before_script:
    - "${PIP} install conan"
    - conan config install https://github.com/Hopobcn/conan-config.git
    - if [ ! -f "$HOME/.conan/profiles/default" ]; then conan profile new default
      --detect ; fi
    - '[ -n "${CONAN_COMPILER_VERSION}" ] && conan profile update settings.compiler.version=${CONAN_COMPILER_VERSION}
      default || true

'
    - '[ -n "${CONAN_LIBCXX_VERSION}" ] && conan profile update settings.compiler.libcxx=${CONAN_LIBCXX_VERSION}
      default || true

'
    - conan profile list
    - conan remote list
    script:
    - mkdir -p build && cd build
    - conan install .. --build=missing
    - if [ "$TRAVIS_OS_NAME" = "osx"     ]; then cmake -DCMAKE_BUILD_TYPE=Release
      .. ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux"   ]; then cmake -DCMAKE_BUILD_TYPE=Release
      .. ; fi
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake -G "Visual Studio 15 Win64"
      .. ; fi
    - cmake --build .
  - stage: deploy
    os: linux
    sudo: required
    language: python
    python: '3.6'
    env:
    - CONAN_GCC_VERSIONS=8
    - CONAN_DOCKER_IMAGE=conanio/gcc8
    - CONAN_PACKAGE_VERSION="0.1.0"
    - CONAN_USERNAME="hopobcn"
    - CONAN_PACKAGE_NAME="simpleton"
    - CONAN_HEADER_ONLY="True"
    - CONAN_UPLOAD="https://api.bintray.com/conan/hopobcn/public"
    - CONAN_CONFIG_URL="https://github.com/Hopobcn/conan-config.git"
    - secure: nE3CACkRiDuh/YXhEuk79w1tFqYjE2df38vvJwNV5+0LKa6DPcSha/iGvjMtFHbkqI4MQh19MBu99GU65tci87zYcMuG+hGvUEpjX9yiLTWfluv6hnH5qjWv5pyFrp8KEMl7nlVahMx/0P2Dp0y3L4UkaB7ijYscvQo6WMdzRJGxHDWFwXr0BRMtRFQst2G7GTbPSyZHXXGfqM/tOA+wuMEKpI17ar0rp2TCIGiUjKHK7GLmkzdAw037QQ1VsXq4Thp+yn5lsj+7NczR3ocrjHE91nxGVh0HMJ9eSNVBSs8OTBNvMoZpRcSiU83Wz9GGililNTZTh8/TNjIeNB9WfIiXXDlVN+O61Ker0w5Yo3Y9bLNuoeGTwrK1ulylPT7lcdFuEmbc65xoRLVaRyB79xTz1QmqSGSdjM5eD+kKzXJrxv4euEUmUvt78WE2/TM9o6cLKY/5v/99WQWEi71r3PU0mp/BF9eCvi8eRAv71/EFg6mZwN4b4ZNBUQxS6ViGc7ZHhWSR+fcSYSWqjFNrNDvIMuuOV4+yAuOEnj+UH6mPtg0PKrRyEddhxdzAAt1Elydp2fqtukVk5rckBTBjcr7pGGT2h5W04yLhmB53tYe0adgSm59r7suEnL1NxfkTDQMBWrd9p0MNaCoLIAql+Msh9vy7lfjFu+FCc9DeKtE=
    services:
    - docker
    install:
    - chmod +x ./conan/ci/install.sh
    - "./conan/ci/install.sh"
    script:
    - chmod +x ./conan/ci/build.sh
    - "./conan/ci/build.sh"
cache:
  directories:
  - "${HOME}/.cache/pip"
